<!-- colors -->
<!ENTITY color_white "rgb(255,255,255)">

<!-- cycleways -->
<!ENTITY color_ncn "rgb(255,0,255)">
<!ENTITY color_rcn "rgb(255,0,255)">
<!ENTITY color_lcn "rgb(255,0,255)">
<!ENTITY color_ncn_text 'black'>
<!ENTITY color_rcn_text 'black'>
<!ENTITY color_lcn_text 'black'>
<!ENTITY color_cycleway_background_text '#ffff00'>
<!ENTITY color_cycleway_background_text_proposed '#ffffff'>
<!ENTITY halo_radius_cycleway '2'>
<!ENTITY halo_radius_cycleway_proposed '1'>
<!ENTITY min_distance_cycleway_text '5'>
<!ENTITY spacing_cycleway_text '200'>
<!ENTITY color_cycleway '#760076'>
<!ENTITY color_cycleway_nobicycle '&color_cycleway;'>
<!ENTITY color_cycleway_traffic '#c300c3'>
<!ENTITY color_cycleway_heavy_traffic '#ff7db9'>
<!ENTITY color_mtb_track 'rgb(0, 100, 0)'>

<!ENTITY text_max_angle '10'>

<!-- hiking tracks -->
<!ENTITY color_kct_yellow 'rgb(248,238,0)'>
<!ENTITY color_kct_red 'rgb(238,0,0)'>
<!ENTITY color_kct_blue 'rgb(0,0,221)'>
<!ENTITY color_kct_green 'rgb(0,221,0)'>
<!ENTITY color_kct_international 'rgb(238,0,0)'>

<!ENTITY color_footway "#ffffc0">
<!ENTITY color_footway_tunnel "#ffffc0">
<!ENTITY color_footway_casing "rgb(128,128,128)">
<!ENTITY color_steps "&color_footway;">
<!ENTITY color_steps_background "rgb(128,128,128)">

<!ENTITY color_bridleway "rgb(0,128,0)">
<!ENTITY color_track_fill "rgb(72,72,72)">
<!ENTITY color_track_casing "rgb(255,255,255)">
<!ENTITY color_track_casing_doubleline "&color_bicycle_casing;">
<!ENTITY color_track_fill_doubleline "#ffffff">
<!ENTITY color_track_fill_doubleline2 "#dddddd">
<!ENTITY color_track_tunnel "rgb(128,128,128)">
<!ENTITY color_track_lozoom "rgb(72,72,72)">

<!ENTITY color_bicycle_track_fill "&color_bicycle;">
<!ENTITY color_bicycle_track_casing "&color_bicycle_casing;">
<!ENTITY color_bicycle_track_tunnel "&color_bicycle;">
<!ENTITY color_bicycle_track_lozoom "rgb(72,72,72)">

<!ENTITY color_bicycle '#c07dc0'>
<!ENTITY color_bicycle_footway '&color_bicycle;'>
<!ENTITY color_bicycle_casing "#333333">

<!ENTITY color_bicycle_tunnel "&color_bicycle;">
<!ENTITY color_bicycle_footway_tunnel "&color_bicycle;">

<!-- highway-roads -->

<!ENTITY color_road '#ffffee'>
<!ENTITY color_residential 'rgb(255,255,255)'>
<!ENTITY color_tertiary '#ffeac3'>
<!ENTITY color_secondary '#e9d2a7'>
<!ENTITY color_primary '#cec4ae'>
<!ENTITY color_motorway '#a0a0a0'>

<!ENTITY opacity_tunnel '1'>
<!ENTITY color_road_tunnel '#ffffff'>
<!ENTITY color_residential_tunnel 'rgb(255,255,255)'>
<!ENTITY color_tertiary_tunnel '#ffeddd'>
<!ENTITY color_secondary_tunnel '#ffeddd'>
<!ENTITY color_primary_tunnel '#ffeddd'>
<!ENTITY color_motorway_tunnel '#ffeddd'>


<!ENTITY color_pedestrian_background 'rgb(128,128,128)'>
<!ENTITY color_road_background '#999999'>
<!ENTITY color_residential_background 'rgb(120,120,120)'>
<!ENTITY color_tertiary_background '#b4b100'>
<!ENTITY color_secondary_background '#c86400'>
<!ENTITY color_primary_background '#a00000'>
<!ENTITY color_motorway_background 'rgb(80,96,119)'>

<!ENTITY color_parking '&color_residential;'>

<!ENTITY color_lozoom '#606060'>
<!ENTITY color_road_lozoom '&color_lozoom;'>
<!ENTITY color_tertiary_lozoom '&color_lozoom;'>
<!ENTITY color_secondary_lozoom '&color_lozoom;'>
<!ENTITY color_primary_lozoom '&color_lozoom;'>

<!ENTITY color_pedestrian "#ffffc3">

<!ENTITY color_pedestrian_bicycle "&color_bicycle;">
<!ENTITY color_pedestrian_bicycle_area "#e2bce2">
<!ENTITY opacity_pedestrian_bicycle "0.5">

<!ENTITY color_raceway "rgb(255,192,203)">

<!ENTITY color_tram "black">
<!ENTITY opacity_tram '0.5'>
<!ENTITY color_railway "rgb(128,128,128)">
<!ENTITY color_railway_tunnel "rgb(177,177,177)">
<!ENTITY color_stations "&color_non_bicycle_amenity;">

<!ENTITY color_non_bicycle_amenity '#6f6f6f'>
<!ENTITY color_bicycle_amenity '#c800da'>

<!ENTITY color_bicycle_shop '&color_bicycle_amenity;'>
<!ENTITY color_police '#666666'>
<!ENTITY color_camp_site 'rgb(0,102,255)'>

<!ENTITY color_food '&color_non_bicycle_amenity;'>
<!ENTITY color_culture '&color_non_bicycle_amenity;'>
<!ENTITY color_embasy '&color_non_bicycle_amenity;'>
<!ENTITY color_accomodation '&color_non_bicycle_amenity;'>
<!ENTITY color_prison '&color_non_bicycle_amenity;'>
<!ENTITY color_fire_station '&color_non_bicycle_amenity;'>
<!ENTITY color_caravan_site '&color_non_bicycle_amenity;'>
<!ENTITY color_parking '&color_non_bicycle_amenity;'>

<!ENTITY color_pharmacy '#666666'>
<!ENTITY color_hospital '&color_non_bicycle_amenity;'>

<!ENTITY color_attraction 'rgb(102,0,51)'>

<!ENTITY color_forest '#cdf0b5'>
<!ENTITY color_wood '#d0dec8'>
<!ENTITY color_grass 'rgb(207,236,168)'>
<!ENTITY color_park 'rgb(182,253,182)'>

<!--
<!ENTITY color_building 'rgb(188,169,169)'>
-->
<!ENTITY color_building '#704141'>
<!ENTITY opacity_building '0.5'>

<!ENTITY color_placenames_text 'rgb(0,0,0)'>
<!ENTITY color_countries_text 'rgb(157,108,157)'>

<!ENTITY color_glacier 'rgb(153,204,255)'>
<!ENTITY color_water_fill 'rgb(114,155,249)'>
<!ENTITY color_water_stroke 'rgb(80,109,177)'>
<!ENTITY color_island 'rgb(242,239,233)'>
<!ENTITY color_water_weir 'rgb(170,170,170)'>
<!ENTITY color_water_fill_tunnel 'rgb(255,255,255)'>
<!ENTITY color_water_text 'rgb(80,109,177)'>

<!ENTITY opacity_cycleway '1'>

<!ENTITY width_track_fill '2'>
<!ENTITY width_track_casing '3'>
<!ENTITY width_track_fill_lozoom '0.6'>
<!ENTITY width_track_casing_lozoom '1'>

<!ENTITY cyclelane_offset_highest_zoom '5'>
<!ENTITY cyclelane_offset_high_zoom '4'>
<!ENTITY cyclelane_offset_medium_zoom '3'>

<!ENTITY color_oneway_arrow '#888cdd'>
<!ENTITY color_bicycle_directions '#a200ff'>
<!ENTITY color_role_directions '&color_cycleway;'>
<!ENTITY spacing_directions '70'>
<!ENTITY spacing_role_directions '70'>
<!ENTITY stroke-width_directions '0.4'>
<!ENTITY stroke_directions 'white'>
<!ENTITY scale_directions '0.6'>
<!ENTITY scale_role_directions '1'>
<!ENTITY offset_directions '4'>
<!ENTITY offset_role_directions '0'>
<!ENTITY offset_directions_high '5'>
