<!ENTITY color_ncn "rgb(255,0,88)">
<!ENTITY color_rcn "rgb(255,0,255)">
<!ENTITY color_lcn "rgb(88,0,255)">

<!ENTITY color_footway "rgb(218, 151, 146)">
<!ENTITY color_steps "&color_footway;">

<!ENTITY color_bridleway "rgb(0,128,0)">

<!ENTITY color_bicycle "rgb(0,0,128)">
<!ENTITY color_bicycle_footway "rgb(75,0,128)">

<!ENTITY color_bicycle_tunnel "rgb(75,75,128)">
<!ENTITY color_bicycle_footway_tunnel "rgb(108,75,129)">

<!ENTITY color_residential "rgb(255, 255, 255)">
<!ENTITY color_tertiary "rgb(204, 204, 204)">
<!ENTITY color_secondary "rgb(252,252,181)">
<!ENTITY color_primary "rgb(254,255,107)">
<!ENTITY color_trunk "rgb(254,255,107)">
<!ENTITY color_motorway "rgb(252,152,53)">

<!ENTITY color_residential_tunnel "rgb(255, 255, 255)">
<!ENTITY color_tertiary_tunnel "rgb(255, 255, 255)">
<!ENTITY color_secondary_tunnel "rgb(252,252,181)">
<!ENTITY color_primary_tunnel "rgb(254,255,107)">
<!ENTITY color_trunk_tunnel "rgb(254,255,107)">
<!ENTITY color_motorway_tunnel "rgb(252,152,53)">

<!ENTITY color_pedestrian "rgb(255,212,212)">
<!ENTITY color_pedestrian_bicycle "rgb(212,212,255)">

<!ENTITY color_tram "rgb(128,128,128)">
