<!-- Style for yellow hiking tracks. -->
<Style name="yellow-track">
  <Rule title="žlutá turistická trasa">
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for red hiking tracks. -->
<Style name="red-track">
  <Rule title="červená turistická trasa">
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for green hiking tracks. -->
<Style name="green-track">
  <Rule title="zelená turistická trasa">
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for blue hiking tracks. -->
<Style name="blue-track">
  <Rule title="modrá turistická trasa">
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with red ones. -->
<Style name="yellow-red-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with green ones. -->
<Style name="yellow-green-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with blue ones. -->
<Style name="yellow-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for red hiking tracks together with green ones. -->
<Style name="red-green-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for red hiking tracks together with blue ones. -->
<Style name="red-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for green hiking tracks together with blue ones. -->
<Style name="green-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for red hiking tracks together with green and blue ones. -->
<Style name="red-green-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with green and blue ones. -->
<Style name="yellow-green-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with red and blue ones. -->
<Style name="yellow-red-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with green and red ones. -->
<Style name="yellow-red-green-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for all four hiking tracks together. -->
<Style name="yellow-red-green-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-16</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for international hiking tracks. -->
<Style name="international-track">
  <Rule title="mezinárodní turistická trasa">
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_international;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="mezinárodní turistická trasa">
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_international;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="mezinárodní turistická trasa">
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_international;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="mezinárodní turistická trasa">
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_international;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="mezinárodní turistická trasa">
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_international;</CssParameter>
      <CssParameter name="stroke-opacity">0.8</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>


<Style name="symbols">
    <Rule title="rozcestí tras KČT">
      &maxscale_zoom14;
      <Filter>[amenity]='signpost' or [information]='guidepost'</Filter>
      <PointSymbolizer file= "&symbols-path;signpost2.png" type="png" width="12" height="24"/>
    </Rule>
</Style>

<Style name="text">
    <Rule>
            <Filter>[amenity]='signpost' or [information]='guidepost'</Filter>
            &maxscale_zoom14;
            <TextSymbolizer name="name" fontset_name="oblique-fonts" size="10" fill="#000000" dy="-16" vertical_alignment="top" allow_overlap="true" halo_radius="1" wrap_width="30"/>
    </Rule>
    <Rule>
            <Filter>[amenity]='signpost' or [information]='guidepost'</Filter>
            &maxscale_zoom16;
            <TextSymbolizer name="ele" fontset_name="oblique-fonts" size="10" fill="#000000" dy="5" vertical_alignment="bottom" allow_overlap="true" halo_radius="1" wrap_width="30"/>
    </Rule>
</Style>
