<!ENTITY color_background "#EADFCF">

<!ENTITY color_building '#FCCCD2'>

<!ENTITY color_industrial '#D0D0D0'>
<!ENTITY color_parking '#D0D0D0'>
<!ENTITY color_construction '#D0D0D0'>

<!ENTITY color_barrier '#444'>
<!ENTITY width_barrier '1'>

<!ENTITY opacity_construction '1'>

<!ENTITY stroke_width_railway "2">
<!ENTITY stroke_width_tram "1">

<!ENTITY stroke_width_footway "2">
<!ENTITY stroke_width_cycleway "2">
<!ENTITY stroke_width_track "3.5">
<!ENTITY stroke_width_bridleway "2">
<!ENTITY stroke_width_path "1">

<!ENTITY color_track "white">
<!ENTITY color_footway "white">
<!ENTITY color_cycleway "white">
<!ENTITY color_bridleway "white">
<!ENTITY color_path "white">

<!ENTITY color_steps "gray">

<!ENTITY color_footway_casing "#BDBDBD">
<!ENTITY color_pedestrian "white">
<!ENTITY color_living_street "white">

<!ENTITY color_living_street_casing "#BDBDBD">

<!ENTITY color_tram_stop_text "#DA1B8A">
<!ENTITY color_station_text "black">
<!ENTITY color_halt_text "black">
<!ENTITY color_subway_station_text "#66f">
<!ENTITY color_station_disused_text "grey">
<!ENTITY color_subway_station_disused_text "grey">

<!ENTITY color_tram "#DA1B8A">
<!ENTITY color_railway "black">
<!ENTITY color_tertiary '#E9E9E9'>
<!ENTITY color_secondary '#D3D3D3'>
<!ENTITY color_primary '#C9C9C9'>
<!ENTITY color_trunk '#BFBFBF'>
<!ENTITY color_motorway '#BFBFBF'>

<!ENTITY color_park '#73C82C'>
<!ENTITY color_landuse_residential "#B3E3B7">
<!ENTITY color_allotments '#B3E3B7'>
