<!ENTITY color_background "#EAE3D8">

<!ENTITY color_building '#FCBCC5'>

<!ENTITY color_industrial '#D0D0D0'>
<!ENTITY color_parking '#D0D0D0'>
<!ENTITY color_construction '#D0D0D0'>
<!ENTITY color_institution '#D0D0D0'>

<!ENTITY color_barrier '#444'>
<!ENTITY width_barrier '1'>

<!ENTITY opacity_construction '1'>

<!ENTITY stroke_width_railway "1.25">
<!ENTITY stroke_width_railway_z13 "1">
<!ENTITY stroke_width_railway_z10_12 "0.75">
<!ENTITY stroke_width_tram "1">

<!ENTITY stroke_width_footway_z13 "1">
<!ENTITY stroke_width_footway "2">
<!ENTITY stroke_width_cycleway_z13 "1">
<!ENTITY stroke_width_cycleway "2">
<!ENTITY stroke_width_track_z13 "1.5">
<!ENTITY stroke_width_track "3">
<!ENTITY stroke_width_bridleway_z13 "1">
<!ENTITY stroke_width_bridleway "2">
<!ENTITY stroke_width_path_z13 "0.5">
<!ENTITY stroke_width_path "1">

<!ENTITY color_track "white">
<!ENTITY color_footway "white">
<!ENTITY color_cycleway "white">
<!ENTITY color_bridleway "white">
<!ENTITY color_path "white">

<!ENTITY color_highway_platform "white">
<!ENTITY color_railway_platform "white">
<!ENTITY color_tram_platform "white">

<!ENTITY color_highway_platform_casing "#0092DA">
<!ENTITY color_railway_platform_casing "gray">
<!ENTITY color_tram_platform_casing "#DA1B8A">

<!ENTITY color_steps "gray">

<!ENTITY color_footway_casing "#BDBDBD">
<!ENTITY color_pedestrian "white">
<!ENTITY color_living_street "white">

<!ENTITY color_living_street_casing "#BDBDBD">

<!ENTITY color_bus_site "#0092DA">
<!ENTITY color_tram_site "#DA1B8A">
<!ENTITY opacity_site "0.2">

<!ENTITY color_bus_stop_text "#0092DA">
<!ENTITY color_tram_stop_text "#DA1B8A">
<!ENTITY color_station_text "black">
<!ENTITY color_halt_text "black">
<!ENTITY color_subway_station_text "#7981B0">
<!ENTITY color_station_disused_text "grey">
<!ENTITY color_subway_station_disused_text "grey">

<!ENTITY color_tree_row "#4EAF6A">

<!ENTITY color_ferry_route "blue">
<!ENTITY color_tram "#DA1B8A">
<!ENTITY color_railway "black">
<!ENTITY color_tertiary '#E9E9E9'>
<!ENTITY color_secondary '#D3D3D3'>
<!ENTITY color_primary '#C9C9C9'>
<!ENTITY color_trunk '#BFBFBF'>
<!ENTITY color_motorway '#BFBFBF'>

<!-- greenery colors -->
<!ENTITY color_forest '#CDDE87'>
<!ENTITY color_grave_yard '#B3E3B7'>
<!ENTITY color_cemetery '#AACBAF'>
<!ENTITY color_park '#73C82C'>
<!ENTITY color_meadow '#73C82C'>
<!ENTITY color_scrub '#B3E3B7'>
<!ENTITY color_orchard '#B3E3B7'>
<!ENTITY color_vineyard '#B3E3B7'>
<!ENTITY color_village_green '#B3E3B7'>
<!ENTITY color_landuse_residential "#B3E3B7">
<!ENTITY color_allotments '#B3E3B7'>
<!ENTITY color_garden "#73C82C">
<!ENTITY color_common_leisure "#73C82C">

<!ENTITY color_placenames_text '#2A3E92'>
<!ENTITY color_road_text '#2A3E92'>
<!ENTITY color_area_text '#2A3E92'>
<!ENTITY color_island_text '#2A3E92'>

<!ENTITY color_countries_text 'rgb(157,108,157)'>

<!ENTITY color_no_access 'white'>
<!ENTITY opacity_no_access '0.6'>

<!ENTITY color_paid_access 'white'>
<!ENTITY opacity_paid_access '0.3'>
