<!ENTITY color_building '#FCCCD2'>

<!ENTITY color_industrial '#D0D0D0'>

<!ENTITY stroke_width_railway "2">
<!ENTITY stroke_width_tram "1">

<!ENTITY color_tram "#DA1B8A">
<!ENTITY color_railway "black">
<!ENTITY color_tertiary '#E9E9E9'>
<!ENTITY color_secondary '#D3D3D3'>
<!ENTITY color_primary '#C9C9C9'>
<!ENTITY color_trunk '#BFBFBF'>
<!ENTITY color_motorway '#BFBFBF'>

<!ENTITY color_park '#73C82C'>
